# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: Version $NEXT_MAJOR_VERSION
# Most plugins within the Jellyfin Org uses a single-digit versioning. Can be replaced by semver: $MAJOR.$MINOR.$PATCH
# https://github.com/release-drafter/release-drafter#next-version-variables
tag-template: v$NEXT_MAJOR_VERSION
version-template: $MAJOR

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: ":fire: Removed"
    label: removed
  - title: ":rewind: Reverted Changes"
    labels:
      - revert
      - reverted
  - title: ":rocket: Major features and improvements"
    labels:
      - major-enhancement
  - title: ":ambulance: Major bug fixes"
    labels:
      - major-bug
  - title: ":wastebasket:️ Deprecated"
    label: deprecated
  - title: ":tada: New features and improvements"
    labels:
      - enhancement
      - feature
  - title: ":bug: Bug Fixes"
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: ":arrow_up: Dependency updates"
    label: dependencies # Default label used by Dependabot
  - title: ":construction_worker: CI & build changes"
    labels:
      - ci
      - build
  - title: ":memo: Documentation updates"
    label: documentation
  - title: ":white_check_mark: Tests"
    labels:
      - test
      - tests
exclude-labels:
  - no-changelog
  - skip-changelog
  - invalid

template: |
  <!-- Optional: add a release summary here -->
  <!-- FIXME: [Plugin build can be downloaded here](<url to version download>) -->
  
  ## :sparkles: What's New
  
  $CHANGES

